apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DiptoChakrabarty/learn_devops_with_projects
    targetRevision: helm_Argo
    path: deploy_helm_apps_argocd/webserver
    helm:
      releaseName: webserver
      valueFiles:
      - values.yaml
  destination:
    namespace: webserver
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated: {}
